apiVersion: v1
kind: Service
metadata:
  name: helloweb
  namespace: hello
  labels:
    app: hello
spec:
  selector:
    app: hello
    tier: web
  ports:
  - port: 8029
    targetPort: 8080
    NodePort: 32301
  type: NodePort
