apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloweb-default
  labels:
    app: hello-default
spec:
  selector:
    matchLabels:
      app: hello-default
      tier: web
  template:
    metadata:
      labels:
        app: hello-default
        tier: web
    spec:
      containers:
      - name: hello-app
        image: gcr.io/google-samples/hello-app:1.0
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 200m
