apiVersion: v1
kind: Service
metadata:
  name: helloweb-default
  labels:
    app: hello-default
spec:
  selector:
    app: hello-default
    tier: web
  ports:
  - port: 8099
    targetPort: 8080
  type: LoadBalancer
